variables:
  GOTOOLCHAIN: local

build giphy proxy docker:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:latest
  stage: build
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
  - docker build -t $CI_REGISTRY_IMAGE/giphyproxy:latest giphyproxy
  - docker push $CI_REGISTRY_IMAGE/giphyproxy:latest
  only:
  - master
